class DataProduct {
  String file_gambar = "";
  String judul = "";
  String harga = "";
  String deskripsi = "";

  DataProduct(this.file_gambar, this.judul, this.harga, this.deskripsi) {}
}

List<DataProduct> dataPasarRebo = <DataProduct>[
  DataProduct('image_lotte/keripik.jpeg', 'Keripik', 'Rp. 2.500,-', 'Keripik... Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad quas labore dolores nostrum rem, provident, impedit, praesentium ut magnam voluptate dolor nobis sequi vel vero nisi iure quidem? Aspernatur error totam ea? Laborum, ad iste dolorem adipisci, voluptate quidem eius doloribus quasi fuga, nihil harum placeat non quos ex porro.'),
  DataProduct('image_lotte/lays.jpeg', 'Lays', 'Rp. 4.500,-', 'Lays... Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad quas labore dolores nostrum rem, provident, impedit, praesentium ut magnam voluptate dolor nobis sequi vel vero nisi iure quidem? Aspernatur error totam ea? Laborum, ad iste dolorem adipisci, voluptate quidem eius doloribus quasi fuga, nihil harum placeat non quos ex porro.'),
  DataProduct('image_lotte/mie.jpeg', 'Mie', 'Rp. 5.500,-', 'Mie.. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad quas labore dolores nostrum rem, provident, impedit, praesentium ut magnam voluptate dolor nobis sequi vel vero nisi iure quidem? Aspernatur error totam ea? Laborum, ad iste dolorem adipisci, voluptate quidem eius doloribus quasi fuga, nihil harum placeat non quos ex porro.'),
  DataProduct('image_lotte/nestle.jpeg', 'Nestle', 'Rp. 8.500,-', 'Nestle Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad quas labore dolores nostrum rem, provident, impedit, praesentium ut magnam voluptate dolor nobis sequi vel vero nisi iure quidem? Aspernatur error totam ea? Laborum, ad iste dolorem adipisci, voluptate quidem eius doloribus quasi fuga, nihil harum placeat non quos ex porro.'),
  DataProduct('image_lotte/nissin.jpeg', 'Nissin', 'Rp. 9.500,-', 'Nissin Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad quas labore dolores nostrum rem, provident, impedit, praesentium ut magnam voluptate dolor nobis sequi vel vero nisi iure quidem? Aspernatur error totam ea? Laborum, ad iste dolorem adipisci, voluptate quidem eius doloribus quasi fuga, nihil harum placeat non quos ex porro.'),
  DataProduct('image_lotte/sarden.jpeg', 'Sarden', 'Rp. 9.500,-', 'Sarden...Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad quas labore dolores nostrum rem, provident, impedit, praesentium ut magnam voluptate dolor nobis sequi vel vero nisi iure quidem? Aspernatur error totam ea? Laborum, ad iste dolorem adipisci, voluptate quidem eius doloribus quasi fuga, nihil harum placeat non quos ex porro.'),
];

List<DataProduct> dataPakansari = <DataProduct>[
  DataProduct('image_pakansari/bika.jpeg', 'Bika', 'Rp. 10.500,-', 'Bika... Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad quas labore dolores nostrum rem, provident, impedit, praesentium ut magnam voluptate dolor nobis sequi vel vero nisi iure quidem? Aspernatur error totam ea? Laborum, ad iste dolorem adipisci, voluptate quidem eius doloribus quasi fuga, nihil harum placeat non quos ex porro.'),
  DataProduct('image_pakansari/floridina.jpeg', 'Floridina', 'Rp. 4.500,-', 'Floridina... Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad quas labore dolores nostrum rem, provident, impedit, praesentium ut magnam voluptate dolor nobis sequi vel vero nisi iure quidem? Aspernatur error totam ea? Laborum, ad iste dolorem adipisci, voluptate quidem eius doloribus quasi fuga, nihil harum placeat non quos ex porro.'),
  DataProduct('image_pakansari/jala.jpeg', 'Jala', 'Rp. 6.500,-', 'Jala... Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad quas labore dolores nostrum rem, provident, impedit, praesentium ut magnam voluptate dolor nobis sequi vel vero nisi iure quidem? Aspernatur error totam ea? Laborum, ad iste dolorem adipisci, voluptate quidem eius doloribus quasi fuga, nihil harum placeat non quos ex porro.'),
  DataProduct('image_pakansari/mie-2.jpeg', 'Mie Goreng', 'Rp. 3.500,-', 'Mie Goreng... Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad quas labore dolores nostrum rem, provident, impedit, praesentium ut magnam voluptate dolor nobis sequi vel vero nisi iure quidem? Aspernatur error totam ea? Laborum, ad iste dolorem adipisci, voluptate quidem eius doloribus quasi fuga, nihil harum placeat non quos ex porro.'),
  DataProduct(
      'image_pakansari/nii_green_tea.jpeg', 'Nii Green Tea', 'Rp. 6.500,-', 'Nii Green Tea... Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad quas labore dolores nostrum rem, provident, impedit, praesentium ut magnam voluptate dolor nobis sequi vel vero nisi iure quidem? Aspernatur error totam ea? Laborum, ad iste dolorem adipisci, voluptate quidem eius doloribus quasi fuga, nihil harum placeat non quos ex porro.'),
  DataProduct('image_pakansari/criptos.jpeg', 'Criptos', 'Rp. 9.500,-', 'Criptos... Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad quas labore dolores nostrum rem, provident, impedit, praesentium ut magnam voluptate dolor nobis sequi vel vero nisi iure quidem? Aspernatur error totam ea? Laborum, ad iste dolorem adipisci, voluptate quidem eius doloribus quasi fuga, nihil harum placeat non quos ex porro.'),
  DataProduct('image_pakansari/nutriboost.jpeg', 'Nutriboost', 'Rp. 7.500,-', 'Nutriboost... Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad quas labore dolores nostrum rem, provident, impedit, praesentium ut magnam voluptate dolor nobis sequi vel vero nisi iure quidem? Aspernatur error totam ea? Laborum, ad iste dolorem adipisci, voluptate quidem eius doloribus quasi fuga, nihil harum placeat non quos ex porro.'),
  DataProduct('image_pakansari/kembar.jpeg', 'kembar', 'Rp. 10.000,-', 'Kembar... Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad quas labore dolores nostrum rem, provident, impedit, praesentium ut magnam voluptate dolor nobis sequi vel vero nisi iure quidem? Aspernatur error totam ea? Laborum, ad iste dolorem adipisci, voluptate quidem eius doloribus quasi fuga, nihil harum placeat non quos ex porro.'),
  DataProduct('image_pakansari/teh_pucuk.jpeg', 'Teh Pucuk', 'Rp. 3.500,-', 'Teh pucuk... Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad quas labore dolores nostrum rem, provident, impedit, praesentium ut magnam voluptate dolor nobis sequi vel vero nisi iure quidem? Aspernatur error totam ea? Laborum, ad iste dolorem adipisci, voluptate quidem eius doloribus quasi fuga, nihil harum placeat non quos ex porro.'),
];
